[package]
name = "rust-macro-pg"
version = "0.1.0"
authors = ["scott munro <scottnmunro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
